### ISSUE TITLE
Doors unlocked (false positive?)

### ISSUE THREAD

**Issue by mm98** [audiconnect/audi_connect_ha#495]
**Describe the bug**
Has there been any changes in regards to `locked` state? The last week I've had doors shown as `unlocked`, but every `state` in the remaining entities (single door locked or open) show it is locked. Kind of hard to explain. 

**To Reproduce**
Not possible to define.

**Expected behavior**
When looking at the other open / lock entities, the cars should be locked. The `myAudi` app is also showing it as locked and safely parked.

**Screenshots**
![image](https://github.com/user-attachments/assets/67199928-28fe-46cc-adf4-f199b7834981)

![image](https://github.com/user-attachments/assets/bd160b71-1f36-42bb-8f12-47f4e686fe8a)

**Logfile**
[home-assistant_audiconnect_2024-11-14T07-17-12.494Z.log](https://github.com/user-attachments/files/17744723/home-assistant_audiconnect_2024-11-14T07-17-12.494Z.log)

**Your Vehicle Details**
Model: A5 Sportback Advanced 40 TFSI 
Year: 2021
Type (Gas/Hybrid/Electric): Gas
Region (EU/US/CA/CN): EU

**Comment by jocxfin** [comment]
Same here. myAudi reports everything as locked and the car is locked, but the integration reports the status as unlocked

**Comment by jocxfin** [comment]
[#471 ](https://github.com/audiconnect/audi_connect_ha/pull/471) this is the cause

**Comment by zenyagami** [comment]
Same issue with me

**Comment by wessa66** [comment]
Role back to 1.10.2 that solved the problem for me , I couldn´t lock start preheater but all info was updated and correct

**Comment by Svarstad** [comment]
> Role back to 1.10.2 that solved the problem for me , I couldn´t lock start preheater but all info was updated and correct

That worked out for me as well, also averageElectricEngineConsumption and averageFuelConsumption turned up, which i was missing. So it seems like some attributes has been gone in the last 2 updates.

**Comment by mm98** [comment]
**Status:**

Yes, it still happens. Currently rolled back to the previous version.

**Comment by ciddi89** [comment]
> **Status:**
> 
> Yes, it still happens. Currently rolled back to the previous version.

yes, for me too.

**Comment by coreywillwhat** [comment]
@Kolbi we may need to roll back #471 or taking a closer look. Just FYI

**Comment by Kolbi** [comment]
Bug seems to be here: https://github.com/audiconnect/audi_connect_ha/blob/0d2116e16b76a25aa432913dc752495060cffa27/custom_components/audiconnect/dashboard.py#L223

**Comment by Kolbi** [comment]
But I'm currently unsure if doors_trunk_status really should be the trigger for the lock....

**Comment by Kolbi** [comment]
For now I undo #471 with https://github.com/audiconnect/audi_connect_ha/pull/527 - @mm98 if you want help please feel free to contribute :)

**Comment by mm98** [comment]
> For now I undo [#471](https://github.com/audiconnect/audi_connect_ha/pull/471) with [#527](https://github.com/audiconnect/audi_connect_ha/pull/527) - [@mm98](https://github.com/mm98) if you want help please feel free to contribute :)

Sure. I'll download the update and test immediately!

**Comment by Kolbi** [comment]
To-Do: State of doors_trunk_state shouldn't be "Open", "Locked" or "Unlocked" use technical values (1, 2, 3?) instead to ensure "translations". 
https://github.com/audiconnect/audi_connect_ha/blob/202b9b8203d7cdba9c8c24f868d0febf154b2e41/custom_components/audiconnect/audi_connect_account.py#L1452

**Comment by mm98** [comment]
> For now I undo [#471](https://github.com/audiconnect/audi_connect_ha/pull/471) with [#527](https://github.com/audiconnect/audi_connect_ha/pull/527) - [@mm98](https://github.com/mm98) if you want help please feel free to contribute :)

This fixed it! Thanks! 🥳

This didn't solve the `lock` and `unlock` actions failing though. Strange. Works in `myAudi` app.
```
This error originated from a custom integration.

Logger: custom_components.audiconnect.util
Source: custom_components/audiconnect/util.py:26
integration: Audi Connect (documentation, issues)
First occurred: 10:17:51 (2 occurrences)
Last logged: 10:21:21

Unable to unlock wauzzzf55ma031567: 404, message='Not Found', url='https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/rlu/v1/Audi/DE/vehicles/{REDACTED}/actions'
Unable to lock wauzzzf55ma031567: 404, message='Not Found', url='https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/rlu/v1/Audi/DE/vehicles/{REDACTED}/actions'
```

Locked:
![Image](https://github.com/user-attachments/assets/02ee163d-2d19-4f64-b9c7-40d6118764e2)

Unlocked:
![Image](https://github.com/user-attachments/assets/2e3886e9-2441-44db-9708-c9e98182ee36)

**Comment by mm98** [comment]
As an extra test I removed the integration and added it back. Just to check if it would change anything regarding the failing lock and unlock actions. It didn't change anything. This is not really a big issue for me. Since I never use the lock/unlock in HA (just reporting).

**Comment by mm98** [comment]
The reported issue was fixed.

**Comment by coreywillwhat** [comment]
> As an extra test I removed the integration and added it back. Just to check if it would change anything regarding the failing lock and unlock actions. It didn't change anything. This is not really a big issue for me. Since I never use the lock/unlock in HA (just reporting).

The endpoint for actions have changed since last summer. This is the reason the actions aren't working. The Cloud Data Refresh endpoint hasn't changed, so thats why we can still see the data.

**Comment by coreywillwhat** [comment]
> To-Do: State of doors_trunk_state shouldn't be "Open", "Locked" or "Unlocked" use technical values (1, 2, 3?) instead to ensure "translations".
> 
> [audi_connect_ha/custom_components/audiconnect/audi_connect_account.py](https://github.com/audiconnect/audi_connect_ha/blob/202b9b8203d7cdba9c8c24f868d0febf154b2e41/custom_components/audiconnect/audi_connect_account.py#L1452)
> 
> Line 1452 in [202b9b8](/audiconnect/audi_connect_ha/commit/202b9b8203d7cdba9c8c24f868d0febf154b2e41)
>  def doors_trunk_status(self):

Agree this needs cleanup. Some points of consideration:
- We have a door lock sensor. So why do we need to use this to show lock or unlock?
- Is the purpose of this to also include the trunk in the doors to determine if anything is unlocked, i would think this should just be included in the doors lock. Is there ever a separate sensor for the lock for the trunk?
- Do we need to include the hood in any of these as well?

We should review all of these sensors and clean them up after discussion to ensure things are included/excluded as we (the community) want them to.

**Comment by blacknell** [comment]
Relates #534
